import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import '@/app/components/Header/Header'
import Header from "@/app/components/Header/Header";
import styles from "@/app/page.module.css";
import Footer from "@/app/components/Footer";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
    return (
        <html lang="en">

        <body className={`${inter.className} ${styles.body}`}>
        <Header />
            {children}
        <Footer/>
        </body>
        </html>
    )
}
